### ISSUE TITLE
[Question] `RotationAlignment` yield not ideal result?

### ISSUE THREAD

**Issue by NatureGeorge** [biocryst/biozernike#7]
Hi! Appreciate your great fascinating work. I am using `biozernike` to perform the global comparison within some PDB structures. And I am exploring the yielded superimposed result using following script (modified from `biozernike/src/test/java/org/rcsb/biozernike/DescriptorTest.java`): 

```java
        public InvariantNorm pipeIN(Structure structure) {
		Atom[] reprAtoms = StructureTools.getRepresentativeAtomArray(structure);
		Point3d[] reprPoints = Calc.atomsToPoints(reprAtoms);
		String[] resNames = Arrays.stream(reprAtoms).map(a -> a.getGroup().getPDBName()).toArray(String[]::new);
		Volume volumeStructure = new Volume();
		volumeStructure.create(reprPoints, resNames);
		return new InvariantNorm(volumeStructure, 6);
	}
        @Test
	public void test1() throws Exception {
		Structure structure_a = StructureIO.getStructure("1ZJK.A");
		Structure structure_b = StructureIO.getStructure("1Q3X.A");
		InvariantNorm normalizationStructure_a = pipeIN(structure_a);
		InvariantNorm normalizationStructure_b = pipeIN(structure_b);
		
		double distance = normalizationStructure_a.compareInvariants(normalizationStructure_b,2);
		//assertTrue(distance<10);

		List<InvariantNorm> zc = new ArrayList<>();
		zc.add(normalizationStructure_b);
		zc.add(normalizationStructure_a);
		AlignmentResult alignmentResult = RotationAlignment.alignMultiple(zc);
		double score = alignmentResult.getScore();
		assertTrue(score<0.4);
		
		Matrix4d rot1 = alignmentResult.getTransforms().get(0);
		Matrix4d rot2 = alignmentResult.getTransforms().get(1);
		rot1.invert();
		rot1.mul(rot2);
		Calc.transform(structure_a, rot1);

		try (PrintWriter out = new PrintWriter("src/test/resources/1ZJK.A.fitted.pdb")) {
			out.println(structure_a.toPDB());
		}
```

I found that the aligned structure pair is not ideal enough:

<table>
    <tr>
    <td>
    <img src="https://user-images.githubusercontent.com/43134199/126901275-7c1d3868-1f34-448c-b8f2-89500d2a1d5a.png">
    </td>
    <td>
    <img src="https://user-images.githubusercontent.com/43134199/126901243-af13e720-714a-440d-b9f0-b588138bfe76.png">
    </td>
<td>
    <img src="https://user-images.githubusercontent.com/43134199/126901252-b546b3a6-8ecf-4150-938b-6a69701d88c7.png">
    </td>
<td>
    <img src="https://user-images.githubusercontent.com/43134199/126901234-ba78f819-b289-4637-acc2-f47dc9d22ffb.png">
    </td>
    </tr>
    <tr><td>1Q3X.A</td><td>1Q3X.A & 1ZJK.A (jFATCAT rigid)</td><td>1Q3X.A & 1ZJK.A (RotationAlignment)</td><td>1Q3X.A & 1ZJK.A (all)</td>
    </tr>
</table>

Perhaps it results from the different sizes of two chains? Or something wrong with my code?

**Comment by biocryst** [comment]
Hi!
I think your code is fine, just this comparison ventures into the 'partial' alignment territory, which is not supported here.
We are aligning volumes (the whole things at once) that fit into a ball of certain radius from a certain center. jFATCAT builds alignment bottom-up from the structure fragments.

The current implementation takes the center as the center of mass of the given volume and the radius is 1.8 * radius of gyration of the molecule -- something we determined works well enough in the cases where the structures are similar to begin with. In the two structures you show these parameters will differ because of the extra domain.

You can override those calculations, experiment with the centers/radii, and if they are close enough between the structures (whatever they are) you'd get a better alignment, maybe even a near-perfect one. However, finding the optimal center/radius automatically for the partial matches is non-trivial. 

I was thinking to implement this using CATH/ECOD/... domain labelling: e.g., find if there are matching domains in the structures and align those independently and then see If the obtained rotations/translations are consistent, etc. But never got around to doing it :)

**Comment by NatureGeorge** [comment]
Got the idea. Thank you!
